name: Continuous Integration
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          

      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Start Selenium Server HUB
        run: nohup java -jar selenium-server-4.17.0.jar hub & sleep 10
        shell: bash

      - name: Start Selenium Server nodes
        run: nohup java -jar selenium-server-4.17.0.jar node --port 5555 --selenium-manager true & sleep 10
        shell: bash

      - name: Run tests
        run: |
          python -m unittest tests/ui_test/test_login_page.py
          python -m unittest tests_runner/api_test_runner.py
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results